export const SEARCH_LOCATION='SEARCH_LOCATION';
export const FETCH_RESTAURANTS='FETCH_RESTAURANTS';
export const LOADING ='LOADING';
export const FETCH_RESTAURANT='FETCH_RESTAURANT';
export const FETCH_REVIEWS = 'FETCH_REVIEWS';
// export const FETCH_GEOLOCATION='FETCH_GEOLOCATION';